export const CHAT_UPLOAD_LIMIT_BYTES = {
  image: 8 * 1024 * 1024,
  video: 50 * 1024 * 1024,
  audio: 15 * 1024 * 1024,
  document: 25 * 1024 * 1024,
} as const;

export const CHAT_ALLOWED_MIME_TYPES = [
  "image/jpeg",
  "image/jpg",
  "image/png",
  "image/webp",
  "image/gif",
  "video/mp4",
  "video/webm",
  "video/quicktime",
  "audio/webm",
  "audio/ogg",
  "audio/mpeg",
  "audio/mp3",
  "audio/wav",
  "audio/x-wav",
  "audio/mp4",
  "audio/aac",
  "application/pdf",
  "text/plain",
  "text/csv",
  "application/msword",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  "application/vnd.ms-excel",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  "application/vnd.ms-powerpoint",
  "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  "application/zip",
  "application/x-zip-compressed",
  "application/x-rar-compressed",
  "application/vnd.rar",
  "application/x-7z-compressed",
] as const;

export const SESSION_INVALID_ERROR_CODES = [
  "AUTH_REQUIRED",
  "INVALID_TOKEN",
  "USER_NOT_FOUND",
  "SOCKET_AUTH_REQUIRED",
] as const;

export const SOCKET_EVENTS = {
  joinChat: "join_chat",
  chatMessage: "chat_message",
  chatMessageUpdated: "chat_message_updated",
  chatUpdated: "chat_updated",
  chatRead: "chat_read",
  userStatus: "user_status",
  typingStart: "typing_start",
  typingStop: "typing_stop",
  serverError: "server_error",
  callStart: "call:start",
  callIncoming: "call:incoming",
  callAccept: "call:accept",
  callAccepted: "call:accepted",
  callReject: "call:reject",
  callRejected: "call:rejected",
  callEnd: "call:end",
  callEnded: "call:ended",
  callSignal: "call:signal",
} as const;
